### ISSUE TITLE
Current package will not download, new version available

### ISSUE THREAD

**Issue by mavhc** [guillaume-ferry/geogebra-classic#1]
https://download.geogebra.org/installers/6.0/GeoGebra-Windows-Installer-6-0-760-0.exe

**Comment by MCKN007** [comment]
在linux上可以通过apt命令安装，但是无法运行      
Attempt to load file %F
Cannot open file
libva error: vaGetDriverNames() failed with unknown libva error
[24757:0930/100157.011822:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
zsh: trace trap  geogebra-classic %F
